name: GitHub Classroom Workflow

on:
  pull_request:
    types: [opened, reopened]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '19'
      - uses: education/autograding@v1
